### ISSUE TITLE
Script error after moving a pallet into a sell point

### ISSUE THREAD

**Issue by GMNGjoy** [loki79uk/FS25_LumberJack#9] opened 2024-11-24 06:18 UTC
Single instance of this error, shortly after installing Lumberjack 1.0.0.1

Map: Riverbend Springs
Game Version: Farming Simulator 25 (Steam) Version: 1.2.1.0 b31303

### Steps to reproduce? 
1. Enable Lumberjack (1.0.0.1)
2. Buy / create pallet in game
3. Move pallet with super strength into sell point 

### Actual
the following log error was looping infinitely (after pallet sold), causing inability to continue without restarting the game.

> 2024-11-23 22:05 Error: Running LUA method 'update'.
> dataS/scripts/handTools/specializations/HandToolHands.lua:728: attempt to perform arithmetic (div) on nil and number

**Comment by loki79uk** [comment] 2024-11-24 10:49
All I do with lumberjack at the moment for superstrength is call (and hook) the console command to enable/disable it.   All the other stuff should only happen when holding the chainsaw, although I do look in a table:  `g_localPlayer.targeter.closestTargetsByKey`, but I don't see how this could lead to a division by nil/zero.

I tried selling some pallets and bales and all seemed normal..  It could be just a rare base game error that happens with superstrength active, i.e. calculating a normalised vector with zero distance, or for a missing object.

Please add a comment here if you can reproduce! (applies to anyone reading this)

**Comment by loki79uk** [comment] 2024-12-04 23:08
I think this was just a one off.  Closing as not a bug.

**Closed by loki79uk** 2024-12-04 23:08 UTC
